project:
  type: book
  output-dir: docs
  # pre-render:
  #   - table_formating.R

book:
  title: "CCCSTBench-Book benchmarking CCC tools integrating pathway information"
  reader-mode: true
  # only working witb a website project
  # announcement:
  #     icon: info-circle
  #     dismissable: true
  #     content: "This website is still under active development - all content subject to change"
  #     type: primary
  #     position: below-navbar
  author: "Bastien CHASSAGNOL"
  date: last-modified
  page-navigation: true
 # cover-image: cover.jpg
 # favicon: cover.jpg
  repo-url: https://github.com/bastienchassagnol/CCCSTBench-Book
  site-url: https://bastienchassagnol.github.io/CCCSTBench-Book
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  open-graph: true
  downloads: [pdf, docx]
  sidebar:
    style: "floating"
    collapse-level: 2
    border: true
    search: true
  chapters:
    - index.qmd
    - intro.qmd
  appendices:
    - references.qmd
    - tools.qmd
  page-footer:
    center:  |
       Written by Bastien CHASSAGNOL and Marie-Pier. We used This book was built with <a href="https://quarto.org/">Quarto</a>.
    background: "#f8f9fa"
    border: false
    right:
      - icon: github
        href: https://github.com/bastienchassagnol/CCCSTBench-Book.git

## global metadata options, whatever the format
# quarto extensions
filters:
  - highlight-text
  - webp-to-png
number-depth: 3
number-sections: true # Required for cross-referencing sections
# bibliographic options
bibliography: assets/cellcommunication.bib
link-citations: true
highlight-style: github
# code options
execute:
  echo: false
  eval: true
  message: false
  warning: false
  error: false
  freeze: auto # to avoid using lots of GH actions + complex fonts managements with pdf output.
# Table options
tbl-cap-location: bottom
keywords:
  - Benchmark
  - Cell-cell communication tools
  - spatial transcriptomics
  - single-cell
# document metadata
lang: en-GB
subject: "Cell-cell benchmark"

format:
  html:
    # styling options
    page-layout: full
    theme:
      light: [cosmo, assets/css/style-utiltr.scss]
      dark:  [darkly, assets/css/style-utiltr.scss]
    css:
      - assets/css/style-reactable.css
      - assets/css/style-utiltr.css
    include-in-header:
      - file: banner_announcement.js
      - text: |
          <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700&display=fallback" rel="stylesheet">
    lightbox: true
    author-meta: "Bastien CHASSAGNOL, and Marie-Pier"
    toc-expand: 3
    comments:
      hypothesis: true
    # code options
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
    code-block-border-left: "#31BAE9"
    code-copy: true
    code-link: true
    code-overflow: wrap
    collapse: true
    smooth-scroll: true
  docx:
    toc-title: Contents
    # reference-doc: custom-reference-doc.docx To add a docx reference.
  pdf:
    documentclass: book
    keep-tex: true # for litterature publishers
    # package installation
    pdf-engine: xelatex # supports fonts installation
    latex-auto-install: true
    # Bibliographic outputs
    colourlinks: true
    cite-method: biblatex
    # Generates list of figures and tables
    lof: true
    lot: true
    crossref:
      lof-title: "List of Figures"
      lot-title: "List of Tables"
    # include-in-header:
    #   text: |
    #     \usepackage[backend=biber, sorting=nty]{biblatex}
    # \usepackage{imakeidx}
    # \makeindex[intoc=true, columns=2, columnseprule=true]
    # include-after-body:
    #   text: |
    #     \printindex

editor: source

