on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 17 * * 5"  # Runs every Friday at 18:00 CET (17:00 UTC)
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: render-${{ github.event_name != 'pull_request' || github.run_id }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install ImageMagick (for automated webp conversion)
        uses: mfinelli/setup-imagemagick@v6.0.0       


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true # required for pdf outputs

      - name: Install R version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install LOCAL Renv R Dependencies 
        uses: r-lib/actions/setup-renv@v2

      # Install extra R dependencies not listed in renv
      - name: Install R packages
        run: |
          Rscript -e "install.packages('gdtools', dependencies = TRUE)"  # Install gfonts from CRAN
          Rscript -e "install.packages('curl')"  # Two packages somehow related to gdtools
          Rscript -e "install.packages('gfonts')"  # Install gfonts from CRAN
          Rscript -e "install.packages('downlit')"  # Automated linking of R functions
            
      - name: "Install 'Google Fonts'"
        run: |
          fontreq=$(Rscript -e "cat(gdtools::install_gfont_script(family = 'Open Sans'))")
          echo "fontreq='$fontreq'"
          sudo -s eval "$fontreq"
        shell: bash

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
